### ISSUE TITLE
api 데이터 DB 저장

### ISSUE THREAD

**Issue by leejyohan** [2022-2-CTS/Node-Back-End#1]
api 데이터에는 사진이 없어서 크롤링으로 사진 불러온 뒤, DB에 저장해야할 것 같습니다

**Comment by bluebluerabbit** [comment]
routes/crawl.js 수행 시, 각 행사의 포스터 이미지 경로를 크롤링하여 routes/event/json 경로에 '<event>_json.json' 파일로 저장됩니다. JSON 파일 읽어서 DB에 저장해주세요.
